AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ServiceName:
    Type: String
  MinecraftImage:
    Type: String
  ContainerPort:
    Type: Number
    Default: 25565
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref ServiceName, Cluster]]
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties: 
      Family: !Join ['', [!Ref ServiceName, TaskDefinition]]
      ContainerDefinitions: 
        - Essential: yes
          Image: "repository-url/image:tag"
          MountPoints: 
            - SourceVolume: minecraft-efs-volume
              ContainerPath: /minecraft
              ReadOnly: no
          Name: !Ref ServiceName
          # Send logs to CloudWatch Logs
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
      Cpu: "1024"
      Memory: "4096"
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - "FARGATE"
      Volumes: 
        - Name: minecraft-efs-volume
          EfsVolumeConfiguration:
            - FileSystemId: minecraft-file-system
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinition]]
